socialClone/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'
urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(), name='signup')
]

socialClone/posts/urls.py
from django.urls import path, re_path
from . import views
app_name = 'posts'

urlpatterns =[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    re_path(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='single'),
    re_path(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),

]

socialClone/socialClone/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups'))

]

socialClone/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" 
   integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
   <!-- latest minified js-->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" 
   integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

   <!--Fonts-->
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet">
   <!-- custom css-->
   <link rel="stylesheet" href="{% static 'socialClone/css/master.css' %}">

</head>
<body>
    <nav class="navbar mynav" role="navigation",id="navbar">
       <div class="container">
           <a  class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
           <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li><a href="{% url 'posts:create' %}">Post</a></li>
              <li><a href="{% url 'groups:all' %}">Groups</a></li>
              <li><a href="{% url 'groups:create' %}">Create Group</a></li>
              <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
              {% else %}
              <li><a href="{% url 'groups:all' %}">Groups</a></li>
              <li><a href="{% url 'accounts:login' %}">Log In</a></li>
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              {% endif %}
           </ul>
       </div> 
    </nav>
    <div class="container mycontent">
    {% block content %}
     
     {% endblock %}
    </div>
</body>
</html>

socialClone/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to socialClone</h1>
{% endblock %}

socialClone/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in!</h1>
{% endblock %}

socialClone/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting ..come back soon!
</h1>
{% endblock %}